### ISSUE TITLE
Seg fault on simple DPP optimization

### ISSUE THREAD

**Issue by spfrommer** [cvxpy/cvxpy#1555]
**Describe the bug**
A simple DPP optimization produces a seg fault when pre multiplying by a constant.

**To Reproduce**
```
import cvxpy as cp
import numpy as np

a = cp.Variable((1, 1))
b = cp.Variable((1,))

param = cp.Parameter(1)

constraints = []
objective = cp.Minimize(
    # cp.sum_squares(a) - b @ (2 * param) # no seg fault
    cp.sum_squares(a) - 2 * b @ param # seg fault
)

problem = cp.Problem(objective, constraints)

param.value = np.array([1])
problem.solve(verbose=True)
```

**Expected behavior**
The code should not produce a seg fault.

**Output**
```text
===============================================================================
                                     CVXPY                                     
                                    v1.1.17                                    
===============================================================================
(CVXPY) Nov 17 01:34:57 PM: Your problem has 2 variables, 0 constraints, and 1 parameters.
(CVXPY) Nov 17 01:34:57 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Nov 17 01:34:57 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Nov 17 01:34:57 PM: Compiling problem (target solver=OSQP).
(CVXPY) Nov 17 01:34:57 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Nov 17 01:34:57 PM: Applying reduction CvxAttr2Constr
(CVXPY) Nov 17 01:34:57 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Nov 17 01:34:57 PM: Applying reduction QpMatrixStuffing
Segmentation fault (core dumped)
```

**Version**
 - OS: Ubuntu 18.04
 - CVXPY Version: 1.1.17

**Additional context**
Not sure why the ordering of the multiplication matters.

**Comment by SteveDiamond** [comment]
I looked into this, and the issue only comes up when ``a`` and ``b`` are scalars. If you increase the dimension of ``b`` the problem goes away. So there must be a bug somewhere around special casing of scalars.

**Comment by rileyjmurray** [comment]
Chiming in. NumPy behaves as follows
```
>>> np.array([[1]]) @ np.array(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

>>> np.array([1]) @ np.array(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
```
Of course, the problem should be fixed, and cvxpy makes no claims that we mimic numpy, but it's worth noting.

I think the issue might be that we make assumptions that the size of some expressions is a nonempty tuple. The code below would produce a segfault if it was implemented directly in C/C++.
```
>>> np.array(1).shape
()

>>> np.array(1).shape[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: tuple index out of range
```

**Comment by rodfloripa** [comment]
Was it fixed?

**Comment by SteveDiamond** [comment]
Fixed in https://github.com/cvxpy/cvxpy/pull/1556

**Comment by rodfloripa** [comment]
I installed cvxpy now from source but I still get the segmentation error running the code from @spfrommer 

===============================================================================
                                     CVXPY                                     
                                    v1.1.17                                    
===============================================================================
(CVXPY) Nov 20 07:50:36 PM: Your problem has 2 variables, 0 constraints, and 1 parameters.
(CVXPY) Nov 20 07:50:36 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Nov 20 07:50:36 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Nov 20 07:50:36 PM: Compiling problem (target solver=OSQP).
(CVXPY) Nov 20 07:50:36 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Nov 20 07:50:36 PM: Applying reduction CvxAttr2Constr
(CVXPY) Nov 20 07:50:36 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Nov 20 07:50:36 PM: Applying reduction QpMatrixStuffing
[1]    67 segmentation fault (core dumped)  python t.py

**Comment by SteveDiamond** [comment]
We haven't merged in the patch yet. It still needs to be approved. So the source code is not updated yet.
