### ISSUE TITLE
`fracify` fails to work

### ISSUE THREAD

**Issue by Wu-Chenyang** [cvxpy/cvxpy#1685]
**Describe the bug**
The function `fracify` function `utilities/power_tools.py` seems to have some bugs. It fails to convert a weight vector into a dyadic weight vector.

**To Reproduce**
```python
import cvxpy as cp
p = cp.Variable(5)
cp.geo_mean(p, np.array([1/8, 1/6, 1/12, 3/16, 7/16]))
```

**Expected behavior**
Normally, it should return a proper constraint.

**Output**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wucy/.local/lib/python3.9/site-packages/cvxpy/atoms/geo_mean.py", line 223, in __init__
    self.tree = decompose(self.w_dyad)
  File "/home/wucy/.local/lib/python3.9/site-packages/cvxpy/utilities/power_tools.py", line 592, in decompose
    raise ValueError('input must be a dyadic weight vector. got: {}'.format(w_dyad))
ValueError: input must be a dyadic weight vector. got: (Fraction(1, 8), Fraction(1, 6), Fraction(1, 12), Fraction(3, 16), Fraction(7, 16))
```

**Version**
 - OS: Ubuntu 20.04
 - CVXPY Version: 1.1.18

**Additional context**

**Comment by rileyjmurray** [comment]
The problem is that [dyad_completion](https://github.com/cvxpy/cvxpy/blob/df238d99a885d91fd2c0eacc3b9b4d2ff6c3c261/cvxpy/utilities/power_tools.py#L404) doesn't always work.
```
w_frac
Out[9]: 
(Fraction(1, 8),
 Fraction(1, 6),
 Fraction(1, 12),
 Fraction(3, 16),
 Fraction(7, 16))
dyad_completion(w_frac)
Out[10]: 
(Fraction(1, 8),
 Fraction(1, 6),
 Fraction(1, 12),
 Fraction(3, 16),
 Fraction(7, 16))
```
I've fixed it and made a PR.

**Comment by Wu-Chenyang** [comment]
It still fails to work in some instances. I list some of them below,
```
cp.geo_mean(p, np.array([14., 108., 110., 77., 6.]))
cp.geo_mean(p, np.array([15., 4., 8., 0., 9.]))
cp.geo_mean(p, np.array([14., 21., 217., 57., 6.]))
cp.geo_mean(p, np.array([3., 36., 77., 8., 8.]))
```

**Comment by rileyjmurray** [comment]
@Wu-Chenyang thanks for following-up. Can you please try the change in PR #1688?

**Comment by Wu-Chenyang** [comment]
Great work! It works perfectly right now. Thank you 👍

**Comment by Wu-Chenyang** [comment]
Oh, it fails again when the denominator is too large. This could happen even when the input integer is relatively small. Is it solvable?

**Comment by rileyjmurray** [comment]
You can increase ``max_denom``, other than that there is no magic bullet as of now. (There are potential ways to make it more robust but we don't have the manpower for that right now.)

**Comment by Wu-Chenyang** [comment]
Is there a potential downside of using a large `max_denom`?

**Comment by rileyjmurray** [comment]
I believe it will result in larger optimization problems (i.e., more variables) and potentially numerical inaccuracies with the solver. You can definitely give it a shot, but you should make sure to solve with ``verbose=True`` and inspect the solver output. It would also be good to manually check constraint violations.

**Comment by Wu-Chenyang** [comment]
I just had a try, and everything seems alright. Thanks!

**Comment by rileyjmurray** [comment]
Resolved by #1688
